"""Pydantic 스키마"""

from .auth import TokenResponse
from .user import UserCreate, UserResponse, UserUpdate
from .paper import (
    PaperListItem,
    PaperDetail,
    PaginatedResponse,
    PaperStats,
    AuthorResponse,
)
from .chat import (
    Reference,
    AskFilters,
    AskRequest,
    AskReferencesEvent,
    AskTokenEvent,
    AskDoneEvent,
    ConversationCreate,
    ConversationUpdate,
    ConversationResponse,
    ConversationListItem,
    MessageCreate,
    MessageResponse,
    AnswerLogResponse,
    PaginatedConversations,
    PaginatedMessages,
)
from .agent import (
    AgentAskRequest,
    SubTaskSchema,
    ComplexityEvent,
    SubtasksEvent,
    TaskStartEvent,
    TaskCompleteEvent,
    AgentStatusEvent,
    AgentDoneEvent,
    AgentExecutionMetadata,
)
from .podcast import (
    PodcastFilters,
    PodcastGoalRequest,
    PaperSelectionRequest,
    SubscriptionCreateRequest,
    SubscriptionUpdateRequest,
    DialogueTurn,
    DialogueScript,
    PodcastReference,
    TaskResult,
    EpisodeResponse,
    EpisodeListItem,
    SubscriptionResponse,
    PodcastStatusEvent,
    PodcastTaskStartEvent,
    PodcastTaskCompleteEvent,
    PodcastSearchResultsEvent,
    PodcastScriptChunkEvent,
    PodcastDoneEvent,
    PodcastErrorEvent,
    PaginatedEpisodes,
    PaginatedSubscriptions,
)

__all__ = [
    # Auth
    "TokenResponse",
    # User
    "UserCreate",
    "UserResponse",
    "UserUpdate",
    # Paper
    "PaperListItem",
    "PaperDetail",
    "PaginatedResponse",
    "PaperStats",
    "AuthorResponse",
    # Chat
    "Reference",
    "AskFilters",
    "AskRequest",
    "AskReferencesEvent",
    "AskTokenEvent",
    "AskDoneEvent",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationListItem",
    "MessageCreate",
    "MessageResponse",
    "AnswerLogResponse",
    "PaginatedConversations",
    "PaginatedMessages",
    # Agent
    "AgentAskRequest",
    "SubTaskSchema",
    "ComplexityEvent",
    "SubtasksEvent",
    "TaskStartEvent",
    "TaskCompleteEvent",
    "AgentStatusEvent",
    "AgentDoneEvent",
    "AgentExecutionMetadata",
    # Podcast
    "PodcastFilters",
    "PodcastGoalRequest",
    "PaperSelectionRequest",
    "SubscriptionCreateRequest",
    "SubscriptionUpdateRequest",
    "DialogueTurn",
    "DialogueScript",
    "PodcastReference",
    "TaskResult",
    "EpisodeResponse",
    "EpisodeListItem",
    "SubscriptionResponse",
    "PodcastStatusEvent",
    "PodcastTaskStartEvent",
    "PodcastTaskCompleteEvent",
    "PodcastSearchResultsEvent",
    "PodcastScriptChunkEvent",
    "PodcastDoneEvent",
    "PodcastErrorEvent",
    "PaginatedEpisodes",
    "PaginatedSubscriptions",
]
